Feature: Improve extraction
neos/metadata-extractor pull request #3
Opened 2017-01-06 08:37 UTC by daniellienert

2017-01-06 08:38 UTC, daniellienert commented
@ComiR: Pleas review ;)

2017-01-10 16:27 UTC, ComiR requested changes
I'll leave a PR on your branch shortly.

2017-01-10 16:27 UTC, ComiR commented on Classes/Domain/ExtractionManager.php
> +use Neos\Media\Domain\Model\ImageVariant;
Don't use the new Namespace just yet.

2017-01-10 16:27 UTC, ComiR commented on Classes/Converter/NumberConverter.php
> +    public static function convertBinaryToVersion($binaryVersion) {
adhere to [PSR-2](http://www.php-fig.org/psr/psr-2/) ("Opening braces for methods MUST go on the next line, and closing braces MUST go on the next line after the body.").

2017-01-10 16:27 UTC, ComiR commented on Classes/Domain/Extractor/AbstractExtractor.php
> +    public static function isSuitableFor($mediaType)
could make use of `TYPO3\Flow\Utility\MediaTypes::mediaRangeMatches()`.

2017-01-10 16:27 UTC, ComiR commented on Classes/Domain/Extractor/ExifExtractor.php
> +    protected $exifData = null;
`null` is always the default value - no need to define it here.

2017-01-10 16:27 UTC, ComiR commented on Classes/Domain/Extractor/ExifExtractor.php
> +        $deprecatedOrUnmappedProperties = [
I'd move these (and those below) in static properties to maintain them more easily. Any objections?

2017-01-10 16:27 UTC, ComiR commented on Classes/Domain/Extractor/ExtractorInterface.php
> +    public static function isSuitableFor($mediaType);
I propose changing the parameter from `string $mediaType` to `FlowResource $resource` to be able to determine the suitability using other properties (f.e. file size).

2017-01-10 16:27 UTC, ComiR commented on Classes/Domain/Extractor/ExifExtractor.php
> +    public function canHandleExtraction(FlowResource $resource)
I'd propose throwing an exception if extraction can't be handled instead of using this method. Then we can use the extractors as singletons.

2017-01-10 16:27 UTC, ComiR commented on Classes/Domain/Extractor/IptcIimExtractor.php
> +        $iptcData['IntellectualGenres'] = $iim->getProperty(Iptc\Iim::OBJECT_ATTRIBUTE_REFERENCE);
I'd put these mappings in a static property here too.

2017-01-10 16:27 UTC, ComiR commented on Classes/Domain/Extractor/IptcIimExtractor.php
> +    public function canHandleExtraction(FlowResource $resource)
see https://github.com/neos/metadata-extractor/pull/3#discussion_r95370594

2017-02-09 21:16 UTC, daniellienert commented on Classes/Domain/Extractor/ExtractorInterface.php
> +    public static function isSuitableFor($mediaType);
Done

2017-02-09 21:47 UTC, daniellienert commented on Classes/Domain/Extractor/ExifExtractor.php
> +    public function canHandleExtraction(FlowResource $resource)
Done.

2017-02-09 21:48 UTC, merged