TASK: Refactor and fix date converter
neos/metadata-extractor pull request #7
Opened 2017-02-18 09:17 UTC by daniellienert

2017-02-18 09:27 UTC, daniellienert commented
@ComiR: This time fixed for real (hopefully). Review appreciated.

2017-02-21 08:36 UTC, ComiR requested changes
Only some remarks in regard to code styling. Apart from that LGTM by reading.

2017-02-21 08:36 UTC, ComiR commented on Classes/Domain/Extractor/IptcIimExtractor.php
> +
style issue

2017-02-21 08:36 UTC, ComiR commented on Classes/Domain/Extractor/IptcIimExtractor.php
> +    protected function readRawIptcData(FlowResource $resource)
could even be declared `static`.

2017-02-21 08:36 UTC, ComiR commented on Tests/Unit/Domain/Extractor/Converter/DateConverterTest.php
> +    public function convertGpsDateAndTime($timeStamp, $dateStamp, $expected)
I'd switch `$timeStamp` and `$dateStamp` to match `DateConverter::convertGpsDateAndTime`.

2017-03-11 08:50 UTC, merged